RhinoKernel: /mnt/d/6_workSpace/55_lora/4_node/2_ASR6501/2_code/4_3/alios-asr-lora-4.3_rel/include/aos/list.h File Reference
list.h File Reference
Data Structures
struct dlist_s
struct slist_s
Macros
#define aos_offsetof(type, member) ((size_t)&(((type *)0)->member))
#define aos_container_of(ptr, type, member) ((type *) ((char *) (ptr) - aos_offsetof(type, member)))
#define dlist_entry(addr, type, member) ((type *)((long)addr - aos_offsetof(type, member)))
#define AOS_DLIST_INIT(list) {&(list), &(list)}
#define dlist_first_entry(ptr, type, member) dlist_entry((ptr)->next, type, member)
#define dlist_for_each(pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
#define dlist_for_each_safe(pos, n, head)
#define dlist_for_each_entry(queue, node, type, member)
#define dlist_for_each_entry_safe(queue, n, node, type, member)
#define list_entry(ptr, type, member) aos_container_of(ptr, type, member)
#define dlist_for_each_entry_reverse(pos, head, member, type)
#define AOS_DLIST_HEAD_INIT(name) { &(name), &(name) }
#define AOS_DLIST_HEAD(name) dlist_t name = AOS_DLIST_HEAD_INIT(name)
#define slist_for_each_entry(queue, node, type, member)
#define slist_for_each_entry_safe(queue, tmp, node, type, member)
#define AOS_SLIST_HEAD_INIT(name) {0}
#define AOS_SLIST_HEAD(name) slist_t name = AOS_SLIST_HEAD_INIT(name)
#define slist_entry(addr, type, member)
#define slist_first_entry(ptr, type, member) slist_entry((ptr)->next, type, member)
Typedefs
typedef struct dlist_s dlist_t
typedef struct slist_s slist_t
Functions
static void __dlist_add (dlist_t *node, dlist_t *prev, dlist_t *next)
static void dlist_add (dlist_t *node, dlist_t *queue)
static void dlist_add_tail (dlist_t *node, dlist_t *queue)
static void dlist_del (dlist_t *node)
static void dlist_init (dlist_t *node)
static void INIT_AOS_DLIST_HEAD (dlist_t *list)
static int dlist_empty (const dlist_t *head)
static int dlist_entry_number (dlist_t *queue)
static void slist_add (slist_t *node, slist_t *head)
static void slist_add_tail (slist_t *node, slist_t *head)
static void slist_del (slist_t *node, slist_t *head)
static int slist_empty (const slist_t *head)
static void slist_init (slist_t *head)
static int slist_entry_number (slist_t *queue)
Macro Definition Documentation
aos_offsetof
#define aos_offsetof (type, member) ((size_t)&(((type *)0)->member))
aos_container_of
#define aos_container_of (ptr, type, member) ((type *) ((char *) (ptr) - aos_offsetof(type, member)))
dlist_entry
#define dlist_entry (addr, type, member) ((type *)((long)addr - aos_offsetof(type, member)))
AOS_DLIST_INIT
#define AOS_DLIST_INIT (list) {&(list), &(list)}
dlist_first_entry
#define dlist_first_entry (ptr, type, member) dlist_entry((ptr)->next, type, member)
dlist_for_each
#define dlist_for_each (pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
dlist_for_each_safe
#define dlist_for_each_safe (pos, n, head)
Value:
for (pos = (head)->next, n = pos->next; pos != (head); \
    pos = n, n = pos->next)
dlist_for_each_entry
#define dlist_for_each_entry (queue, node, type, member)
Value:
for (node = aos_container_of((queue)->next, type, member); \
         &node->member != (queue); \
         node = aos_container_of(node->member.next, type, member))
dlist_for_each_entry_safe
#define dlist_for_each_entry_safe (queue, n, node, type, member)
Value:
for (node = aos_container_of((queue)->next, type, member),  \
         n = (queue)->next ? (queue)->next->next : NULL;        \
         &node->member != (queue);                              \
         node = aos_container_of(n, type, member), n = n ? n->next : NULL)
list_entry
#define list_entry (ptr, type, member) aos_container_of(ptr, type, member)
dlist_for_each_entry_reverse
#define dlist_for_each_entry_reverse (pos, head, member, type)
Value:
for (pos = list_entry((head)->prev, type, member);        \
         &pos->member != (head);                              \
         pos = list_entry(pos->member.prev, type, member))
AOS_DLIST_HEAD_INIT
#define AOS_DLIST_HEAD_INIT (name) { &(name), &(name) }
AOS_DLIST_HEAD
#define AOS_DLIST_HEAD (name) dlist_t name = AOS_DLIST_HEAD_INIT(name)
slist_for_each_entry
#define slist_for_each_entry (queue, node, type, member)
Value:
for (node = aos_container_of((queue)->next, type, member); \
         &node->member;                                        \
         node = aos_container_of(node->member.next, type, member))
slist_for_each_entry_safe
#define slist_for_each_entry_safe (queue, tmp, node, type, member)
Value:
for (node = aos_container_of((queue)->next, type, member),    \
         tmp = (queue)->next ? (queue)->next->next : NULL;        \
         &node->member;                                           \
         node = aos_container_of(tmp, type, member), tmp = tmp ? tmp->next : tmp)
AOS_SLIST_HEAD_INIT
#define AOS_SLIST_HEAD_INIT (name) {0}
AOS_SLIST_HEAD
#define AOS_SLIST_HEAD (name) slist_t name = AOS_SLIST_HEAD_INIT(name)
slist_entry
#define slist_entry (addr, type, member)
Value:
(\
    addr ? (type *)((long)addr - aos_offsetof(type, member)) : (type *)addr \
)
slist_first_entry
#define slist_first_entry (ptr, type, member) slist_entry((ptr)->next, type, member)
Typedef Documentation
dlist_t
typedef struct dlist_s dlist_t
slist_t
typedef struct slist_s slist_t
Function Documentation
__dlist_add()
static void __dlist_add (dlist_t * node, dlist_t * prev, dlist_t * next) inline static
References dlist_s::next, and dlist_s::prev.
Referenced by dlist_add(), and dlist_add_tail().
dlist_add()
static void dlist_add (dlist_t * node, dlist_t * queue) inline static
References __dlist_add(), and dlist_s::next.
dlist_add_tail()
static void dlist_add_tail (dlist_t * node, dlist_t * queue) inline static
References __dlist_add(), and dlist_s::prev.
dlist_del()
static void dlist_del (dlist_t * node) inline static
References dlist_s::next, and dlist_s::prev.
dlist_init()
static void dlist_init (dlist_t * node) inline static
References dlist_s::next, and dlist_s::prev.
INIT_AOS_DLIST_HEAD()
static void INIT_AOS_DLIST_HEAD (dlist_t * list) inline static
References dlist_s::next, and dlist_s::prev.
dlist_empty()
static int dlist_empty (const dlist_t * head) inline static
References dlist_s::next.
dlist_entry_number()
static int dlist_entry_number (dlist_t * queue) inline static
References dlist_s::next.
slist_add()
static void slist_add (slist_t * node, slist_t * head) inline static
References slist_s::next.
Referenced by slist_add_tail().
slist_add_tail()
static void slist_add_tail (slist_t * node, slist_t * head) inline static
References slist_s::next, and slist_add().
slist_del()
static void slist_del (slist_t * node, slist_t * head) inline static
References slist_s::next.
slist_empty()
static int slist_empty (const slist_t * head) inline static
References slist_s::next.
slist_init()
static void slist_init (slist_t * head) inline static
References slist_s::next.
slist_entry_number()
static int slist_entry_number (slist_t * queue) inline static
References slist_s::next.